server {
    # standard HTTPS door with encriptation
    listen      443 ssl;  
    # IPv6 suport  
    listen      [::]:443 ssl;
    server_name mateferr.42.fr;

    # encripted conection information
    ssl_certificate     /etc/nginx/ssl/inception.crt;
    ssl_certificate_key /etc/nginx/ssl/inception.key;
    ssl_protocols       TLSv1.2 TLSv1.3;

    root  /var/www/wordpress;
    index index.php index.html;

    # routes for normal requests
    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    # routes for php files - use php-fpm to execute php code
    location ~ \.php$ {
        include         fastcgi_params;
        fastcgi_pass    wordpress:9000;
        fastcgi_param   SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}
